// Generated by CoffeeScript 1.9.0
var GameMath;

GameMath = (function() {
  function GameMath() {}

  GameMath.prototype.floatToFixed = function(num, dec) {
    if (dec == null) {
      dec = 3;
    }
    return parseFloat(num.toFixed(dec));
  };

  return GameMath;

})();

if (typeof module !== 'undefined' && typeof module.exports !== 'undefined') {
  exports.GameMath = GameMath;
} else {
  window.GameMath = GameMath;
}
